#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#define LAUNCHER_BUILDNUM @LAUNCHER_BUILDNUM@
#define MANIFEST_BASE "@MANIFEST_BASE@/@CMAKE_SYSTEM_NAME@/"
#define SYSTEM_TYPE "@CMAKE_SYSTEM_NAME@"
#define BUILD_TYPE "@CMAKE_BUILD_TYPE@"
#define PATCHER_TITLE "@PATCHER_TITLE@"
#define LAUNCHER_BUILDNUM @LAUNCHER_BUILDNUM@
#define EXECUTABLE "@EXECUTABLE@"
#endif // VERSION_CONFIG_H