find_path(MBEDTLS_INCLUDE_DIRS mbedtls/ssl.h HINTS ${CMAKE_INSTALL_PREFIX}/include)

find_library(MBEDTLS_LIBRARY mbedtls PATHS ${CMAKE_INSTALL_PREFIX}/lib)
find_library(MBEDX509_LIBRARY mbedx509 PATHS ${CMAKE_INSTALL_PREFIX}/lib) 
find_library(MBEDCRYPTO_LIBRARY mbedcrypto PATHS ${CMAKE_INSTALL_PREFIX}/lib)

set(MBEDTLS_LIBRARIES "${MBEDTLS_LIBRARY}" "${MBEDX509_LIBRARY}" "${MBEDCRYPTO_LIBRARY}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MBEDTLS DEFAULT_MSG
    MBEDTLS_INCLUDE_DIRS MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY)

mark_as_advanced(MBEDTLS_INCLUDE_DIRS MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY)
